apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: dim-edge-influxdb
  name: dim-edge-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dim-edge-influxdb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: dim-edge-influxdb
    spec:
      containers:
        - image: quay.io/influxdb/influxdb:2.0.0-beta
          imagePullPolicy: ''
          name: dim-edge-influxdb
          ports:
            - containerPort: 9999
          resources: {}
      restartPolicy: Always
      serviceAccountName: ''
      volumes: null
status: {}
