apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: dim-edge/node
  name: dim-edge/node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dim-edge/node
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: dim-edge/node
    spec:
      containers:
        - image: mintxtinm/dim-edge/node
          imagePullPolicy: Never
          name: dim-edge/node
          ports:
            - containerPort: 9090
            - containerPort: 9000
          # resources:
          #   limits:
          #     cpu: '10m'
          #     memory: '20Mi'
          env:
            - name: INFLUX_ADDRESS
              value: http://dim-edge-influxdb-0:9999
      restartPolicy: Always
      serviceAccountName: ''
      volumes: null
status: {}
