apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: dim-edge/node
  name: dim-edge/node
spec:
  ports:
    - name: '9090'
      port: 9090
      targetPort: 9090
    - name: '9000'
      port: 9000
      targetPort: 9000
  type: LoadBalancer
  selector:
    io.kompose.service: dim-edge/node
status:
  loadBalancer: {}
