// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/auth.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Authorization struct {
	Status               string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string                      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string                      `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string                      `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	OrgID                string                      `protobuf:"bytes,5,opt,name=orgID,proto3" json:"orgID,omitempty"`
	Id                   string                      `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Token                string                      `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	UserID               string                      `protobuf:"bytes,8,opt,name=userID,proto3" json:"userID,omitempty"`
	Org                  string                      `protobuf:"bytes,9,opt,name=org,proto3" json:"org,omitempty"`
	Permissions          []*Authorization_Permission `protobuf:"bytes,10,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Authorization) Reset()         { *m = Authorization{} }
func (m *Authorization) String() string { return proto.CompactTextString(m) }
func (*Authorization) ProtoMessage()    {}
func (*Authorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b501dee55460b0, []int{0}
}

func (m *Authorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authorization.Unmarshal(m, b)
}
func (m *Authorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authorization.Marshal(b, m, deterministic)
}
func (m *Authorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authorization.Merge(m, src)
}
func (m *Authorization) XXX_Size() int {
	return xxx_messageInfo_Authorization.Size(m)
}
func (m *Authorization) XXX_DiscardUnknown() {
	xxx_messageInfo_Authorization.DiscardUnknown(m)
}

var xxx_messageInfo_Authorization proto.InternalMessageInfo

func (m *Authorization) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Authorization) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Authorization) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Authorization) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Authorization) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *Authorization) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Authorization) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Authorization) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Authorization) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *Authorization) GetPermissions() []*Authorization_Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type Authorization_Permission struct {
	Action               string                             `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Resource             *Authorization_Permission_Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *Authorization_Permission) Reset()         { *m = Authorization_Permission{} }
func (m *Authorization_Permission) String() string { return proto.CompactTextString(m) }
func (*Authorization_Permission) ProtoMessage()    {}
func (*Authorization_Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b501dee55460b0, []int{0, 0}
}

func (m *Authorization_Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authorization_Permission.Unmarshal(m, b)
}
func (m *Authorization_Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authorization_Permission.Marshal(b, m, deterministic)
}
func (m *Authorization_Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authorization_Permission.Merge(m, src)
}
func (m *Authorization_Permission) XXX_Size() int {
	return xxx_messageInfo_Authorization_Permission.Size(m)
}
func (m *Authorization_Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Authorization_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Authorization_Permission proto.InternalMessageInfo

func (m *Authorization_Permission) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Authorization_Permission) GetResource() *Authorization_Permission_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type Authorization_Permission_Resource struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OrgID                string   `protobuf:"bytes,4,opt,name=orgID,proto3" json:"orgID,omitempty"`
	Org                  string   `protobuf:"bytes,5,opt,name=org,proto3" json:"org,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authorization_Permission_Resource) Reset()         { *m = Authorization_Permission_Resource{} }
func (m *Authorization_Permission_Resource) String() string { return proto.CompactTextString(m) }
func (*Authorization_Permission_Resource) ProtoMessage()    {}
func (*Authorization_Permission_Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b501dee55460b0, []int{0, 0, 0}
}

func (m *Authorization_Permission_Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authorization_Permission_Resource.Unmarshal(m, b)
}
func (m *Authorization_Permission_Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authorization_Permission_Resource.Marshal(b, m, deterministic)
}
func (m *Authorization_Permission_Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authorization_Permission_Resource.Merge(m, src)
}
func (m *Authorization_Permission_Resource) XXX_Size() int {
	return xxx_messageInfo_Authorization_Permission_Resource.Size(m)
}
func (m *Authorization_Permission_Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Authorization_Permission_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Authorization_Permission_Resource proto.InternalMessageInfo

func (m *Authorization_Permission_Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Authorization_Permission_Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Authorization_Permission_Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Authorization_Permission_Resource) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *Authorization_Permission_Resource) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

// List authorization
type ListAuthorizationParams struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Org                  string   `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	OrgID                string   `protobuf:"bytes,4,opt,name=orgID,proto3" json:"orgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAuthorizationParams) Reset()         { *m = ListAuthorizationParams{} }
func (m *ListAuthorizationParams) String() string { return proto.CompactTextString(m) }
func (*ListAuthorizationParams) ProtoMessage()    {}
func (*ListAuthorizationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b501dee55460b0, []int{1}
}

func (m *ListAuthorizationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAuthorizationParams.Unmarshal(m, b)
}
func (m *ListAuthorizationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAuthorizationParams.Marshal(b, m, deterministic)
}
func (m *ListAuthorizationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAuthorizationParams.Merge(m, src)
}
func (m *ListAuthorizationParams) XXX_Size() int {
	return xxx_messageInfo_ListAuthorizationParams.Size(m)
}
func (m *ListAuthorizationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAuthorizationParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListAuthorizationParams proto.InternalMessageInfo

func (m *ListAuthorizationParams) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ListAuthorizationParams) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ListAuthorizationParams) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *ListAuthorizationParams) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

type ListAuthorizationRes struct {
	Authorization        []*Authorization `protobuf:"bytes,1,rep,name=authorization,proto3" json:"authorization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListAuthorizationRes) Reset()         { *m = ListAuthorizationRes{} }
func (m *ListAuthorizationRes) String() string { return proto.CompactTextString(m) }
func (*ListAuthorizationRes) ProtoMessage()    {}
func (*ListAuthorizationRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b501dee55460b0, []int{2}
}

func (m *ListAuthorizationRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAuthorizationRes.Unmarshal(m, b)
}
func (m *ListAuthorizationRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAuthorizationRes.Marshal(b, m, deterministic)
}
func (m *ListAuthorizationRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAuthorizationRes.Merge(m, src)
}
func (m *ListAuthorizationRes) XXX_Size() int {
	return xxx_messageInfo_ListAuthorizationRes.Size(m)
}
func (m *ListAuthorizationRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAuthorizationRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListAuthorizationRes proto.InternalMessageInfo

func (m *ListAuthorizationRes) GetAuthorization() []*Authorization {
	if m != nil {
		return m.Authorization
	}
	return nil
}

// Create authorization
type CreateAuthorizationParams struct {
	Status               string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string                      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OrgID                string                      `protobuf:"bytes,3,opt,name=orgID,proto3" json:"orgID,omitempty"`
	Permissions          []*Authorization_Permission `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateAuthorizationParams) Reset()         { *m = CreateAuthorizationParams{} }
func (m *CreateAuthorizationParams) String() string { return proto.CompactTextString(m) }
func (*CreateAuthorizationParams) ProtoMessage()    {}
func (*CreateAuthorizationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b501dee55460b0, []int{3}
}

func (m *CreateAuthorizationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthorizationParams.Unmarshal(m, b)
}
func (m *CreateAuthorizationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthorizationParams.Marshal(b, m, deterministic)
}
func (m *CreateAuthorizationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthorizationParams.Merge(m, src)
}
func (m *CreateAuthorizationParams) XXX_Size() int {
	return xxx_messageInfo_CreateAuthorizationParams.Size(m)
}
func (m *CreateAuthorizationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthorizationParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthorizationParams proto.InternalMessageInfo

func (m *CreateAuthorizationParams) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateAuthorizationParams) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateAuthorizationParams) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *CreateAuthorizationParams) GetPermissions() []*Authorization_Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

// Sign in
type SignInParams struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInParams) Reset()         { *m = SignInParams{} }
func (m *SignInParams) String() string { return proto.CompactTextString(m) }
func (*SignInParams) ProtoMessage()    {}
func (*SignInParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b501dee55460b0, []int{4}
}

func (m *SignInParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInParams.Unmarshal(m, b)
}
func (m *SignInParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInParams.Marshal(b, m, deterministic)
}
func (m *SignInParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInParams.Merge(m, src)
}
func (m *SignInParams) XXX_Size() int {
	return xxx_messageInfo_SignInParams.Size(m)
}
func (m *SignInParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInParams.DiscardUnknown(m)
}

var xxx_messageInfo_SignInParams proto.InternalMessageInfo

func (m *SignInParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Authorization)(nil), "protocol.Authorization")
	proto.RegisterType((*Authorization_Permission)(nil), "protocol.Authorization.Permission")
	proto.RegisterType((*Authorization_Permission_Resource)(nil), "protocol.Authorization.Permission.Resource")
	proto.RegisterType((*ListAuthorizationParams)(nil), "protocol.ListAuthorizationParams")
	proto.RegisterType((*ListAuthorizationRes)(nil), "protocol.ListAuthorizationRes")
	proto.RegisterType((*CreateAuthorizationParams)(nil), "protocol.CreateAuthorizationParams")
	proto.RegisterType((*SignInParams)(nil), "protocol.SignInParams")
}

func init() { proto.RegisterFile("protocol/auth.proto", fileDescriptor_78b501dee55460b0) }

var fileDescriptor_78b501dee55460b0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0xf1, 0x9f, 0x64, 0xce, 0xf1, 0x32, 0x86, 0x16, 0x16, 0x2d, 0xec, 0x22, 0xf8, 0x2a,
	0x30, 0xf0, 0x20, 0xbb, 0xde, 0x45, 0x58, 0xd8, 0x08, 0xec, 0x22, 0x78, 0xec, 0x01, 0x34, 0x5b,
	0x24, 0xda, 0x66, 0xcb, 0x48, 0x32, 0xa5, 0x7d, 0x87, 0x3e, 0x4c, 0x1f, 0xa7, 0x6f, 0x53, 0x24,
	0xcb, 0xb2, 0xd3, 0xa6, 0x14, 0x72, 0xa7, 0xef, 0xfb, 0x8e, 0x7c, 0x8e, 0x7f, 0x3a, 0xf0, 0xae,
	0x16, 0x5c, 0xf1, 0x9c, 0xff, 0xff, 0x4c, 0x1a, 0x75, 0x4c, 0x8d, 0x42, 0x51, 0x67, 0x26, 0xb7,
	0x21, 0x4c, 0x37, 0x8d, 0x3a, 0x72, 0xc1, 0x6e, 0x88, 0x62, 0xbc, 0x42, 0xef, 0x61, 0x2c, 0x15,
	0x51, 0x8d, 0xc4, 0xde, 0xd2, 0x5b, 0x4d, 0x32, 0xab, 0xd0, 0x12, 0xe2, 0x82, 0xca, 0x5c, 0xb0,
	0x5a, 0x97, 0x61, 0xdf, 0x84, 0x43, 0x0b, 0x7d, 0x84, 0x49, 0x2e, 0x28, 0x51, 0xb4, 0xd8, 0x28,
	0x1c, 0x98, 0xbc, 0x37, 0x74, 0xda, 0xd4, 0x85, 0x4d, 0xc3, 0x36, 0x75, 0x06, 0x9a, 0xc1, 0x88,
	0x8b, 0xc3, 0x6e, 0x8b, 0x47, 0x26, 0x69, 0x05, 0x7a, 0x03, 0x3e, 0x2b, 0xf0, 0xd8, 0x58, 0x3e,
	0x2b, 0x74, 0x95, 0xe2, 0xff, 0x68, 0x85, 0x5f, 0xb5, 0x55, 0x46, 0xe8, 0x89, 0x1b, 0x49, 0xc5,
	0x6e, 0x8b, 0xa3, 0x76, 0xe2, 0x56, 0xa1, 0xb7, 0x10, 0x70, 0x71, 0xc0, 0x13, 0x63, 0xea, 0x23,
	0xda, 0x42, 0x5c, 0x53, 0x51, 0x32, 0x29, 0x19, 0xaf, 0x24, 0x86, 0x65, 0xb0, 0x8a, 0xd7, 0x49,
	0xda, 0xd1, 0x48, 0x4f, 0x48, 0xa4, 0x7b, 0x57, 0x9a, 0x0d, 0xaf, 0x2d, 0xee, 0x3d, 0x80, 0x3e,
	0xd3, 0xed, 0x49, 0x6e, 0x98, 0x58, 0x60, 0xad, 0x42, 0x3f, 0x20, 0x12, 0x54, 0xf2, 0x46, 0xe4,
	0xd4, 0xd0, 0x8a, 0xd7, 0x9f, 0x5e, 0xee, 0x94, 0x66, 0xf6, 0x4a, 0xe6, 0x2e, 0x2f, 0xfe, 0x42,
	0xd4, 0xb9, 0x08, 0x41, 0xa8, 0xae, 0x6b, 0x6a, 0x5b, 0x99, 0xb3, 0xa5, 0xe4, 0x3b, 0x4a, 0x08,
	0xc2, 0x8a, 0x94, 0xd4, 0x3e, 0x81, 0x39, 0xf7, 0x7c, 0xc3, 0x21, 0x5f, 0x4b, 0x68, 0xe4, 0x08,
	0x25, 0x25, 0xcc, 0x7f, 0x32, 0xa9, 0x4e, 0xc6, 0xdb, 0x13, 0x41, 0x4a, 0xa9, 0x3f, 0xab, 0xc1,
	0x76, 0xad, 0xf5, 0x79, 0x80, 0xde, 0x3f, 0x87, 0x3e, 0xe8, 0xd1, 0x9f, 0x1d, 0x20, 0xf9, 0x0d,
	0xb3, 0x27, 0xed, 0x32, 0x2a, 0xd1, 0x57, 0x98, 0x92, 0xa1, 0x87, 0x3d, 0xf3, 0x54, 0xf3, 0x67,
	0x00, 0x66, 0xa7, 0xd5, 0xc9, 0x9d, 0x07, 0x1f, 0xbe, 0x99, 0xcd, 0x3b, 0xf7, 0x23, 0x97, 0x6f,
	0xb8, 0xfb, 0x89, 0x60, 0x48, 0xf1, 0xd1, 0x56, 0x85, 0x17, 0x6d, 0x55, 0xf2, 0x1d, 0x5e, 0xff,
	0x62, 0x87, 0x6a, 0xd7, 0x4d, 0xb9, 0x80, 0x48, 0xc3, 0x34, 0x2f, 0xd9, 0xce, 0xe9, 0xb4, 0xce,
	0x6a, 0x22, 0xe5, 0x15, 0x17, 0xdd, 0xbb, 0x3b, 0xfd, 0x67, 0x6c, 0xfa, 0x7e, 0x79, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xe9, 0x1f, 0xca, 0x10, 0xf9, 0x03, 0x00, 0x00,
}
