// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/bucket.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bucket struct {
	Id                   string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgID                string                  `protobuf:"bytes,2,opt,name=orgID,proto3" json:"orgID,omitempty"`
	Type                 string                  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string                  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                  `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Rp                   string                  `protobuf:"bytes,6,opt,name=rp,proto3" json:"rp,omitempty"`
	CreatedAt            string                  `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string                  `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Labels               []*Bucket_Label         `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty"`
	RetentionRules       []*Bucket_RetentionRule `protobuf:"bytes,10,rep,name=retentionRules,proto3" json:"retentionRules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{0}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bucket) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *Bucket) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Bucket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bucket) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Bucket) GetRp() string {
	if m != nil {
		return m.Rp
	}
	return ""
}

func (m *Bucket) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Bucket) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Bucket) GetLabels() []*Bucket_Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Bucket) GetRetentionRules() []*Bucket_RetentionRule {
	if m != nil {
		return m.RetentionRules
	}
	return nil
}

type Bucket_Label struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgID                string                   `protobuf:"bytes,2,opt,name=orgID,proto3" json:"orgID,omitempty"`
	Name                 string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Properties           *Bucket_Label_Properties `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Bucket_Label) Reset()         { *m = Bucket_Label{} }
func (m *Bucket_Label) String() string { return proto.CompactTextString(m) }
func (*Bucket_Label) ProtoMessage()    {}
func (*Bucket_Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{0, 0}
}

func (m *Bucket_Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket_Label.Unmarshal(m, b)
}
func (m *Bucket_Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket_Label.Marshal(b, m, deterministic)
}
func (m *Bucket_Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket_Label.Merge(m, src)
}
func (m *Bucket_Label) XXX_Size() int {
	return xxx_messageInfo_Bucket_Label.Size(m)
}
func (m *Bucket_Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket_Label proto.InternalMessageInfo

func (m *Bucket_Label) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bucket_Label) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *Bucket_Label) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bucket_Label) GetProperties() *Bucket_Label_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Bucket_Label_Properties struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucket_Label_Properties) Reset()         { *m = Bucket_Label_Properties{} }
func (m *Bucket_Label_Properties) String() string { return proto.CompactTextString(m) }
func (*Bucket_Label_Properties) ProtoMessage()    {}
func (*Bucket_Label_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{0, 0, 0}
}

func (m *Bucket_Label_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket_Label_Properties.Unmarshal(m, b)
}
func (m *Bucket_Label_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket_Label_Properties.Marshal(b, m, deterministic)
}
func (m *Bucket_Label_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket_Label_Properties.Merge(m, src)
}
func (m *Bucket_Label_Properties) XXX_Size() int {
	return xxx_messageInfo_Bucket_Label_Properties.Size(m)
}
func (m *Bucket_Label_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket_Label_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket_Label_Properties proto.InternalMessageInfo

func (m *Bucket_Label_Properties) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Bucket_Label_Properties) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Bucket_RetentionRule struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	EverySeconds         int32    `protobuf:"varint,2,opt,name=everySeconds,proto3" json:"everySeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucket_RetentionRule) Reset()         { *m = Bucket_RetentionRule{} }
func (m *Bucket_RetentionRule) String() string { return proto.CompactTextString(m) }
func (*Bucket_RetentionRule) ProtoMessage()    {}
func (*Bucket_RetentionRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{0, 1}
}

func (m *Bucket_RetentionRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket_RetentionRule.Unmarshal(m, b)
}
func (m *Bucket_RetentionRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket_RetentionRule.Marshal(b, m, deterministic)
}
func (m *Bucket_RetentionRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket_RetentionRule.Merge(m, src)
}
func (m *Bucket_RetentionRule) XXX_Size() int {
	return xxx_messageInfo_Bucket_RetentionRule.Size(m)
}
func (m *Bucket_RetentionRule) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket_RetentionRule.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket_RetentionRule proto.InternalMessageInfo

func (m *Bucket_RetentionRule) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Bucket_RetentionRule) GetEverySeconds() int32 {
	if m != nil {
		return m.EverySeconds
	}
	return 0
}

type OpRes struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpRes) Reset()         { *m = OpRes{} }
func (m *OpRes) String() string { return proto.CompactTextString(m) }
func (*OpRes) ProtoMessage()    {}
func (*OpRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{1}
}

func (m *OpRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpRes.Unmarshal(m, b)
}
func (m *OpRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpRes.Marshal(b, m, deterministic)
}
func (m *OpRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpRes.Merge(m, src)
}
func (m *OpRes) XXX_Size() int {
	return xxx_messageInfo_OpRes.Size(m)
}
func (m *OpRes) XXX_DiscardUnknown() {
	xxx_messageInfo_OpRes.DiscardUnknown(m)
}

var xxx_messageInfo_OpRes proto.InternalMessageInfo

func (m *OpRes) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OpRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// List all buckets
type ListAllBucketsParams struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Org                  string   `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	OrgID                string   `protobuf:"bytes,4,opt,name=orgID,proto3" json:"orgID,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAllBucketsParams) Reset()         { *m = ListAllBucketsParams{} }
func (m *ListAllBucketsParams) String() string { return proto.CompactTextString(m) }
func (*ListAllBucketsParams) ProtoMessage()    {}
func (*ListAllBucketsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{2}
}

func (m *ListAllBucketsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllBucketsParams.Unmarshal(m, b)
}
func (m *ListAllBucketsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllBucketsParams.Marshal(b, m, deterministic)
}
func (m *ListAllBucketsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllBucketsParams.Merge(m, src)
}
func (m *ListAllBucketsParams) XXX_Size() int {
	return xxx_messageInfo_ListAllBucketsParams.Size(m)
}
func (m *ListAllBucketsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllBucketsParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllBucketsParams proto.InternalMessageInfo

func (m *ListAllBucketsParams) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListAllBucketsParams) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListAllBucketsParams) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *ListAllBucketsParams) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *ListAllBucketsParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListAllBucketsRes struct {
	Bucket               []*Bucket `protobuf:"bytes,1,rep,name=bucket,proto3" json:"bucket,omitempty"`
	Msg                  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListAllBucketsRes) Reset()         { *m = ListAllBucketsRes{} }
func (m *ListAllBucketsRes) String() string { return proto.CompactTextString(m) }
func (*ListAllBucketsRes) ProtoMessage()    {}
func (*ListAllBucketsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{3}
}

func (m *ListAllBucketsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllBucketsRes.Unmarshal(m, b)
}
func (m *ListAllBucketsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllBucketsRes.Marshal(b, m, deterministic)
}
func (m *ListAllBucketsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllBucketsRes.Merge(m, src)
}
func (m *ListAllBucketsRes) XXX_Size() int {
	return xxx_messageInfo_ListAllBucketsRes.Size(m)
}
func (m *ListAllBucketsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllBucketsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllBucketsRes proto.InternalMessageInfo

func (m *ListAllBucketsRes) GetBucket() []*Bucket {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *ListAllBucketsRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Retrieve a bucket
type RetrieveBucketParams struct {
	BucketID             string   `protobuf:"bytes,1,opt,name=bucketID,proto3" json:"bucketID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveBucketParams) Reset()         { *m = RetrieveBucketParams{} }
func (m *RetrieveBucketParams) String() string { return proto.CompactTextString(m) }
func (*RetrieveBucketParams) ProtoMessage()    {}
func (*RetrieveBucketParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{4}
}

func (m *RetrieveBucketParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveBucketParams.Unmarshal(m, b)
}
func (m *RetrieveBucketParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveBucketParams.Marshal(b, m, deterministic)
}
func (m *RetrieveBucketParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBucketParams.Merge(m, src)
}
func (m *RetrieveBucketParams) XXX_Size() int {
	return xxx_messageInfo_RetrieveBucketParams.Size(m)
}
func (m *RetrieveBucketParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBucketParams.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBucketParams proto.InternalMessageInfo

func (m *RetrieveBucketParams) GetBucketID() string {
	if m != nil {
		return m.BucketID
	}
	return ""
}

// Delete a bucket
type DeleteBucketParams struct {
	BucketID             string   `protobuf:"bytes,1,opt,name=bucketID,proto3" json:"bucketID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBucketParams) Reset()         { *m = DeleteBucketParams{} }
func (m *DeleteBucketParams) String() string { return proto.CompactTextString(m) }
func (*DeleteBucketParams) ProtoMessage()    {}
func (*DeleteBucketParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{5}
}

func (m *DeleteBucketParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBucketParams.Unmarshal(m, b)
}
func (m *DeleteBucketParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBucketParams.Marshal(b, m, deterministic)
}
func (m *DeleteBucketParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBucketParams.Merge(m, src)
}
func (m *DeleteBucketParams) XXX_Size() int {
	return xxx_messageInfo_DeleteBucketParams.Size(m)
}
func (m *DeleteBucketParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBucketParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBucketParams proto.InternalMessageInfo

func (m *DeleteBucketParams) GetBucketID() string {
	if m != nil {
		return m.BucketID
	}
	return ""
}

// Retreive a bucket log
type RetreiveBucketLogParams struct {
	BucketID             string   `protobuf:"bytes,1,opt,name=bucketID,proto3" json:"bucketID,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetreiveBucketLogParams) Reset()         { *m = RetreiveBucketLogParams{} }
func (m *RetreiveBucketLogParams) String() string { return proto.CompactTextString(m) }
func (*RetreiveBucketLogParams) ProtoMessage()    {}
func (*RetreiveBucketLogParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{6}
}

func (m *RetreiveBucketLogParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetreiveBucketLogParams.Unmarshal(m, b)
}
func (m *RetreiveBucketLogParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetreiveBucketLogParams.Marshal(b, m, deterministic)
}
func (m *RetreiveBucketLogParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetreiveBucketLogParams.Merge(m, src)
}
func (m *RetreiveBucketLogParams) XXX_Size() int {
	return xxx_messageInfo_RetreiveBucketLogParams.Size(m)
}
func (m *RetreiveBucketLogParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RetreiveBucketLogParams.DiscardUnknown(m)
}

var xxx_messageInfo_RetreiveBucketLogParams proto.InternalMessageInfo

func (m *RetreiveBucketLogParams) GetBucketID() string {
	if m != nil {
		return m.BucketID
	}
	return ""
}

func (m *RetreiveBucketLogParams) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RetreiveBucketLogParams) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type RetreiveBucketLogRes struct {
	Log                  []*RetreiveBucketLogRes_Log `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *RetreiveBucketLogRes) Reset()         { *m = RetreiveBucketLogRes{} }
func (m *RetreiveBucketLogRes) String() string { return proto.CompactTextString(m) }
func (*RetreiveBucketLogRes) ProtoMessage()    {}
func (*RetreiveBucketLogRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{7}
}

func (m *RetreiveBucketLogRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetreiveBucketLogRes.Unmarshal(m, b)
}
func (m *RetreiveBucketLogRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetreiveBucketLogRes.Marshal(b, m, deterministic)
}
func (m *RetreiveBucketLogRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetreiveBucketLogRes.Merge(m, src)
}
func (m *RetreiveBucketLogRes) XXX_Size() int {
	return xxx_messageInfo_RetreiveBucketLogRes.Size(m)
}
func (m *RetreiveBucketLogRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RetreiveBucketLogRes.DiscardUnknown(m)
}

var xxx_messageInfo_RetreiveBucketLogRes proto.InternalMessageInfo

func (m *RetreiveBucketLogRes) GetLog() []*RetreiveBucketLogRes_Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type RetreiveBucketLogRes_Log struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetreiveBucketLogRes_Log) Reset()         { *m = RetreiveBucketLogRes_Log{} }
func (m *RetreiveBucketLogRes_Log) String() string { return proto.CompactTextString(m) }
func (*RetreiveBucketLogRes_Log) ProtoMessage()    {}
func (*RetreiveBucketLogRes_Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_888d0ff48042a613, []int{7, 0}
}

func (m *RetreiveBucketLogRes_Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetreiveBucketLogRes_Log.Unmarshal(m, b)
}
func (m *RetreiveBucketLogRes_Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetreiveBucketLogRes_Log.Marshal(b, m, deterministic)
}
func (m *RetreiveBucketLogRes_Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetreiveBucketLogRes_Log.Merge(m, src)
}
func (m *RetreiveBucketLogRes_Log) XXX_Size() int {
	return xxx_messageInfo_RetreiveBucketLogRes_Log.Size(m)
}
func (m *RetreiveBucketLogRes_Log) XXX_DiscardUnknown() {
	xxx_messageInfo_RetreiveBucketLogRes_Log.DiscardUnknown(m)
}

var xxx_messageInfo_RetreiveBucketLogRes_Log proto.InternalMessageInfo

func (m *RetreiveBucketLogRes_Log) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RetreiveBucketLogRes_Log) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *RetreiveBucketLogRes_Log) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*Bucket)(nil), "protocol.Bucket")
	proto.RegisterType((*Bucket_Label)(nil), "protocol.Bucket.Label")
	proto.RegisterType((*Bucket_Label_Properties)(nil), "protocol.Bucket.Label.Properties")
	proto.RegisterType((*Bucket_RetentionRule)(nil), "protocol.Bucket.RetentionRule")
	proto.RegisterType((*OpRes)(nil), "protocol.OpRes")
	proto.RegisterType((*ListAllBucketsParams)(nil), "protocol.ListAllBucketsParams")
	proto.RegisterType((*ListAllBucketsRes)(nil), "protocol.ListAllBucketsRes")
	proto.RegisterType((*RetrieveBucketParams)(nil), "protocol.RetrieveBucketParams")
	proto.RegisterType((*DeleteBucketParams)(nil), "protocol.DeleteBucketParams")
	proto.RegisterType((*RetreiveBucketLogParams)(nil), "protocol.RetreiveBucketLogParams")
	proto.RegisterType((*RetreiveBucketLogRes)(nil), "protocol.RetreiveBucketLogRes")
	proto.RegisterType((*RetreiveBucketLogRes_Log)(nil), "protocol.RetreiveBucketLogRes.Log")
}

func init() { proto.RegisterFile("protocol/bucket.proto", fileDescriptor_888d0ff48042a613) }

var fileDescriptor_888d0ff48042a613 = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xe3, 0xd8, 0x4d, 0x26, 0x50, 0x95, 0x55, 0x28, 0xab, 0x08, 0xa1, 0xe0, 0x53, 0x4e,
	0x06, 0x05, 0x78, 0x80, 0xa0, 0x08, 0x14, 0x29, 0x52, 0xab, 0xed, 0x99, 0x83, 0x63, 0x4f, 0xad,
	0x15, 0x76, 0xd6, 0xda, 0xdd, 0x54, 0x2a, 0x27, 0x5e, 0x85, 0xd7, 0xe1, 0xc8, 0x13, 0xa1, 0xfd,
	0x71, 0xfe, 0xa5, 0xf6, 0x94, 0x99, 0x6f, 0x76, 0xfe, 0xbe, 0x6f, 0x62, 0x78, 0xdd, 0x48, 0xa1,
	0x45, 0x2e, 0xaa, 0x0f, 0xab, 0x4d, 0xfe, 0x13, 0x75, 0x6a, 0x7d, 0xd2, 0x6b, 0xe1, 0xe4, 0x5f,
	0x17, 0xe2, 0xaf, 0x36, 0x44, 0x2e, 0xa1, 0xc3, 0x0b, 0x1a, 0x8c, 0x83, 0x49, 0x9f, 0x75, 0x78,
	0x41, 0x86, 0x10, 0x09, 0x59, 0x2e, 0xe6, 0xb4, 0x63, 0x21, 0xe7, 0x10, 0x02, 0x5d, 0xfd, 0xd8,
	0x20, 0x0d, 0x2d, 0x68, 0x6d, 0x83, 0xad, 0xb3, 0x1a, 0x69, 0xd7, 0x61, 0xc6, 0x26, 0x63, 0x18,
	0x14, 0xa8, 0x72, 0xc9, 0x1b, 0xcd, 0xc5, 0x9a, 0x46, 0x36, 0xb4, 0x0f, 0x99, 0x7e, 0xb2, 0xa1,
	0xb1, 0xeb, 0x27, 0x1b, 0xf2, 0x16, 0xfa, 0xb9, 0xc4, 0x4c, 0x63, 0x31, 0xd3, 0xf4, 0xc2, 0xc2,
	0x3b, 0xc0, 0x44, 0x37, 0x4d, 0xe1, 0xa3, 0x3d, 0x17, 0xdd, 0x02, 0x24, 0x85, 0xb8, 0xca, 0x56,
	0x58, 0x29, 0xda, 0x1f, 0x87, 0x93, 0xc1, 0xf4, 0x3a, 0x6d, 0x37, 0x4c, 0xdd, 0x76, 0xe9, 0xd2,
	0x84, 0x99, 0x7f, 0x45, 0xbe, 0xc1, 0xa5, 0x44, 0x8d, 0x6b, 0x33, 0x08, 0xdb, 0x54, 0xa8, 0x28,
	0xd8, 0xbc, 0x77, 0x27, 0x79, 0x6c, 0xff, 0x19, 0x3b, 0xca, 0x1a, 0xfd, 0x0d, 0x20, 0xb2, 0x95,
	0x9f, 0xcf, 0x9e, 0x65, 0x2a, 0xdc, 0x63, 0x6a, 0x06, 0xd0, 0x48, 0xd1, 0xa0, 0xd4, 0x1c, 0x95,
	0xe5, 0x70, 0x30, 0x7d, 0x7f, 0x7e, 0xfe, 0xf4, 0x76, 0xfb, 0x90, 0xed, 0x25, 0x8d, 0xe6, 0x00,
	0xbb, 0x88, 0x69, 0x9d, 0x8b, 0x4a, 0x48, 0x3f, 0x8d, 0x73, 0x8e, 0x05, 0xe9, 0x9c, 0x08, 0x32,
	0xfa, 0x0e, 0x2f, 0x0f, 0xb6, 0xdd, 0x6a, 0x1d, 0xec, 0x69, 0x9d, 0xc0, 0x0b, 0x7c, 0x40, 0xf9,
	0x78, 0x87, 0xb9, 0x58, 0x17, 0xca, 0xd6, 0x89, 0xd8, 0x01, 0x96, 0x7c, 0x81, 0xe8, 0xa6, 0x61,
	0xa8, 0x4c, 0x81, 0x5c, 0x14, 0xdb, 0x02, 0xc6, 0x26, 0x14, 0x2e, 0x6a, 0x54, 0x2a, 0x2b, 0xd1,
	0xcf, 0xd0, 0xba, 0xc9, 0xef, 0x00, 0x86, 0x4b, 0xae, 0xf4, 0xac, 0xaa, 0xdc, 0xd2, 0xea, 0x36,
	0x93, 0x59, 0xad, 0xc8, 0x35, 0xc4, 0xe2, 0xfe, 0x5e, 0xa1, 0xb6, 0x85, 0x22, 0xe6, 0x3d, 0xb3,
	0x68, 0xc5, 0x6b, 0xae, 0xfd, 0x10, 0xce, 0x21, 0x57, 0x10, 0x0a, 0x59, 0x7a, 0x8a, 0x8d, 0xb9,
	0xd3, 0xa2, 0x7b, 0x4e, 0x8b, 0x68, 0xa7, 0x45, 0x72, 0x03, 0xaf, 0x0e, 0x27, 0x30, 0x5b, 0x4c,
	0x20, 0x76, 0xff, 0x1e, 0x1a, 0xd8, 0x23, 0xb9, 0x3a, 0x16, 0x87, 0xf9, 0xb8, 0x69, 0x5d, 0xab,
	0xd2, 0xef, 0x65, 0xcc, 0x64, 0x0a, 0x43, 0x86, 0x5a, 0x72, 0x7c, 0x40, 0xf7, 0xd6, 0xaf, 0x34,
	0x82, 0x9e, 0xcb, 0x59, 0xcc, 0x3d, 0x3b, 0x5b, 0x3f, 0xf9, 0x08, 0x64, 0x8e, 0x15, 0xea, 0xe7,
	0x67, 0xfc, 0x80, 0x37, 0xa6, 0x0b, 0xf2, 0xb6, 0xcb, 0x52, 0x94, 0x4f, 0xa7, 0x19, 0x06, 0x9a,
	0x56, 0x87, 0x88, 0x59, 0xdb, 0x60, 0x8a, 0xff, 0x72, 0x17, 0x1a, 0x31, 0x6b, 0x27, 0x7f, 0x02,
	0xb7, 0xc5, 0x41, 0x7d, 0xc3, 0xcc, 0x67, 0x08, 0x2b, 0x51, 0x7a, 0x5a, 0x92, 0x1d, 0x2d, 0xe7,
	0x1e, 0xa7, 0xe6, 0xc7, 0x3c, 0x1f, 0xdd, 0x41, 0xb8, 0x14, 0xe5, 0xf1, 0x41, 0x06, 0xa7, 0x5f,
	0x08, 0x73, 0x7f, 0xbc, 0x6e, 0xef, 0xc4, 0xda, 0xe6, 0x16, 0x36, 0x0a, 0xe5, 0x62, 0xee, 0x05,
	0xf6, 0xde, 0x2a, 0xb6, 0xcd, 0x3f, 0xfd, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x00, 0x00, 0x24,
	0xf2, 0x04, 0x00, 0x00,
}
