// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/main.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("protocol/main.proto", fileDescriptor_9e8e7d5cf664e777) }

var fileDescriptor_9e8e7d5cf664e777 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x51, 0x8b, 0xd3, 0x40,
	0x14, 0x85, 0xf3, 0xb2, 0xbb, 0x7a, 0x29, 0xab, 0x3b, 0x6b, 0x57, 0xc8, 0xca, 0x82, 0x11, 0x5f,
	0x13, 0xd0, 0x17, 0xd1, 0x87, 0x45, 0x5b, 0x91, 0x85, 0x96, 0x6a, 0x83, 0x50, 0x1f, 0xa7, 0xe1,
	0x9a, 0x0e, 0x4d, 0x33, 0x75, 0x72, 0x53, 0xd0, 0x5f, 0xed, 0x4f, 0x90, 0xcc, 0x4c, 0x3a, 0x13,
	0x43, 0x94, 0x7d, 0xec, 0x39, 0xf7, 0x7c, 0x73, 0x7a, 0x33, 0x03, 0x97, 0x7b, 0x25, 0x49, 0x66,
	0xb2, 0x48, 0x76, 0x5c, 0x94, 0xb1, 0xfe, 0xc5, 0x1e, 0xb4, 0x62, 0x78, 0x9d, 0x4b, 0x99, 0x17,
	0x98, 0x68, 0x61, 0x5d, 0x7f, 0x4f, 0x70, 0xb7, 0xa7, 0x9f, 0x66, 0x2c, 0x7c, 0x72, 0xcc, 0x56,
	0x48, 0xf5, 0xde, 0xaa, 0xe3, 0xa3, 0xba, 0xae, 0xb3, 0x2d, 0x92, 0x95, 0xdd, 0x41, 0xbc, 0xa6,
	0x4d, 0x8f, 0xf0, 0xa3, 0x46, 0x65, 0xb9, 0xaf, 0x7e, 0x9f, 0xc1, 0x28, 0x25, 0xa9, 0x30, 0x45,
	0x75, 0x10, 0x19, 0xb2, 0x5b, 0x80, 0xc9, 0x06, 0xb3, 0x6d, 0xda, 0x1c, 0xc3, 0xae, 0x62, 0x53,
	0x2a, 0x6e, 0x4b, 0xc5, 0x1f, 0x9b, 0x52, 0xe1, 0xd3, 0xb8, 0xa5, 0xc5, 0x6e, 0x7a, 0x89, 0x55,
	0x14, 0xb0, 0x37, 0x70, 0x62, 0xb2, 0x63, 0x37, 0xa3, 0x85, 0xcf, 0x5c, 0xf1, 0x5d, 0x15, 0x0e,
	0x20, 0xa3, 0x80, 0xbd, 0x85, 0xd3, 0x54, 0xe4, 0xe5, 0x5d, 0xc9, 0xae, 0xbc, 0xa8, 0x56, 0xfe,
	0x9b, 0x7d, 0x07, 0x67, 0xcd, 0xe4, 0xa2, 0xa6, 0xc1, 0xce, 0xc3, 0xe1, 0x05, 0x9c, 0xcf, 0x44,
	0x45, 0xef, 0x8b, 0xe2, 0x83, 0x5e, 0x63, 0xc5, 0x6e, 0x5c, 0x81, 0xae, 0x63, 0x8b, 0x5c, 0x0f,
	0xf9, 0x66, 0x07, 0x53, 0x38, 0x5f, 0x22, 0x29, 0x81, 0x07, 0x34, 0xba, 0x0f, 0xec, 0x3a, 0x16,
	0xf8, 0xd8, 0xf9, 0x46, 0x8f, 0x02, 0xb6, 0x82, 0x8b, 0xee, 0xec, 0x4c, 0xe6, 0xec, 0x79, 0x17,
	0x84, 0xc2, 0x33, 0x2d, 0xeb, 0xe6, 0x1f, 0x23, 0xa6, 0xdf, 0x2d, 0x8c, 0xa6, 0x58, 0x20, 0xb5,
	0xed, 0x9e, 0xb9, 0x84, 0xaf, 0x5b, 0xde, 0x23, 0xe7, 0x2e, 0xec, 0x47, 0x5e, 0xc1, 0x85, 0xfe,
	0xdf, 0x35, 0x6d, 0xa4, 0x12, 0xbf, 0x38, 0x09, 0x59, 0xfa, 0xd5, 0x7a, 0x66, 0xbf, 0x5a, 0x6f,
	0xc4, 0x90, 0xbf, 0xc2, 0xe5, 0x44, 0x21, 0x27, 0xec, 0xb2, 0x5f, 0x78, 0x17, 0xae, 0x6f, 0x5b,
	0xba, 0x77, 0x2b, 0x3b, 0x76, 0x14, 0xb0, 0x6f, 0x30, 0x6e, 0x77, 0xd9, 0x05, 0xbf, 0xec, 0x7f,
	0x98, 0x7b, 0xa2, 0x13, 0x38, 0xf9, 0x84, 0x34, 0xc7, 0xc1, 0x8b, 0x37, 0x72, 0xd9, 0x39, 0xea,
	0x17, 0xf2, 0xf0, 0x4b, 0xf3, 0x04, 0xa7, 0x9c, 0xb8, 0xff, 0x4a, 0xb4, 0x68, 0xcf, 0x63, 0x7f,
	0xc9, 0x66, 0x39, 0x13, 0x80, 0xbb, 0xb2, 0x42, 0x45, 0x3a, 0x1a, 0xba, 0x19, 0xa7, 0xf6, 0xfb,
	0x3a, 0x4f, 0x43, 0xd6, 0xa7, 0xda, 0x79, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0xee, 0xdc, 0x05,
	0x49, 0x8f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreServiceClient interface {
	// Setup
	CheckSetup(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CheckSetupRes, error)
	Setup(ctx context.Context, in *SetupParams, opts ...grpc.CallOption) (*empty.Empty, error)
	SignIn(ctx context.Context, in *SignInParams, opts ...grpc.CallOption) (*empty.Empty, error)
	SignOut(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Bucket
	ListAllBuckets(ctx context.Context, in *ListAllBucketsParams, opts ...grpc.CallOption) (*ListAllBucketsRes, error)
	RetrieveBucket(ctx context.Context, in *RetrieveBucketParams, opts ...grpc.CallOption) (*Bucket, error)
	RetrieveBucketLog(ctx context.Context, in *RetreiveBucketLogParams, opts ...grpc.CallOption) (*RetreiveBucketLogRes, error)
	DeleteBucket(ctx context.Context, in *DeleteBucketParams, opts ...grpc.CallOption) (*OpRes, error)
	// Auth
	ListAuthorization(ctx context.Context, in *ListAuthorizationParams, opts ...grpc.CallOption) (*ListAuthorizationRes, error)
	CreateAuthorization(ctx context.Context, in *CreateAuthorizationParams, opts ...grpc.CallOption) (*Authorization, error)
	RetrieveAuthorization(ctx context.Context, in *RetrieveAuthorizationParams, opts ...grpc.CallOption) (*Authorization, error)
	GetMe(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Me, error)
	// Query
	QueryData(ctx context.Context, in *QueryParams, opts ...grpc.CallOption) (*QueryRes, error)
	InsertData(ctx context.Context, in *InsertDataParams, opts ...grpc.CallOption) (*InsertDataRes, error)
}

type storeServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoreServiceClient(cc *grpc.ClientConn) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) CheckSetup(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CheckSetupRes, error) {
	out := new(CheckSetupRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/CheckSetup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Setup(ctx context.Context, in *SetupParams, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/Setup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) SignIn(ctx context.Context, in *SignInParams, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) SignOut(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListAllBuckets(ctx context.Context, in *ListAllBucketsParams, opts ...grpc.CallOption) (*ListAllBucketsRes, error) {
	out := new(ListAllBucketsRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/ListAllBuckets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RetrieveBucket(ctx context.Context, in *RetrieveBucketParams, opts ...grpc.CallOption) (*Bucket, error) {
	out := new(Bucket)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/RetrieveBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RetrieveBucketLog(ctx context.Context, in *RetreiveBucketLogParams, opts ...grpc.CallOption) (*RetreiveBucketLogRes, error) {
	out := new(RetreiveBucketLogRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/RetrieveBucketLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteBucket(ctx context.Context, in *DeleteBucketParams, opts ...grpc.CallOption) (*OpRes, error) {
	out := new(OpRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/DeleteBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListAuthorization(ctx context.Context, in *ListAuthorizationParams, opts ...grpc.CallOption) (*ListAuthorizationRes, error) {
	out := new(ListAuthorizationRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/ListAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) CreateAuthorization(ctx context.Context, in *CreateAuthorizationParams, opts ...grpc.CallOption) (*Authorization, error) {
	out := new(Authorization)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/CreateAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RetrieveAuthorization(ctx context.Context, in *RetrieveAuthorizationParams, opts ...grpc.CallOption) (*Authorization, error) {
	out := new(Authorization)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/RetrieveAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetMe(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Me, error) {
	out := new(Me)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/GetMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) QueryData(ctx context.Context, in *QueryParams, opts ...grpc.CallOption) (*QueryRes, error) {
	out := new(QueryRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/QueryData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) InsertData(ctx context.Context, in *InsertDataParams, opts ...grpc.CallOption) (*InsertDataRes, error) {
	out := new(InsertDataRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/InsertData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
type StoreServiceServer interface {
	// Setup
	CheckSetup(context.Context, *empty.Empty) (*CheckSetupRes, error)
	Setup(context.Context, *SetupParams) (*empty.Empty, error)
	SignIn(context.Context, *SignInParams) (*empty.Empty, error)
	SignOut(context.Context, *empty.Empty) (*empty.Empty, error)
	// Bucket
	ListAllBuckets(context.Context, *ListAllBucketsParams) (*ListAllBucketsRes, error)
	RetrieveBucket(context.Context, *RetrieveBucketParams) (*Bucket, error)
	RetrieveBucketLog(context.Context, *RetreiveBucketLogParams) (*RetreiveBucketLogRes, error)
	DeleteBucket(context.Context, *DeleteBucketParams) (*OpRes, error)
	// Auth
	ListAuthorization(context.Context, *ListAuthorizationParams) (*ListAuthorizationRes, error)
	CreateAuthorization(context.Context, *CreateAuthorizationParams) (*Authorization, error)
	RetrieveAuthorization(context.Context, *RetrieveAuthorizationParams) (*Authorization, error)
	GetMe(context.Context, *empty.Empty) (*Me, error)
	// Query
	QueryData(context.Context, *QueryParams) (*QueryRes, error)
	InsertData(context.Context, *InsertDataParams) (*InsertDataRes, error)
}

// UnimplementedStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServiceServer struct {
}

func (*UnimplementedStoreServiceServer) CheckSetup(ctx context.Context, req *empty.Empty) (*CheckSetupRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSetup not implemented")
}
func (*UnimplementedStoreServiceServer) Setup(ctx context.Context, req *SetupParams) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Setup not implemented")
}
func (*UnimplementedStoreServiceServer) SignIn(ctx context.Context, req *SignInParams) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedStoreServiceServer) SignOut(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOut not implemented")
}
func (*UnimplementedStoreServiceServer) ListAllBuckets(ctx context.Context, req *ListAllBucketsParams) (*ListAllBucketsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllBuckets not implemented")
}
func (*UnimplementedStoreServiceServer) RetrieveBucket(ctx context.Context, req *RetrieveBucketParams) (*Bucket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBucket not implemented")
}
func (*UnimplementedStoreServiceServer) RetrieveBucketLog(ctx context.Context, req *RetreiveBucketLogParams) (*RetreiveBucketLogRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBucketLog not implemented")
}
func (*UnimplementedStoreServiceServer) DeleteBucket(ctx context.Context, req *DeleteBucketParams) (*OpRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (*UnimplementedStoreServiceServer) ListAuthorization(ctx context.Context, req *ListAuthorizationParams) (*ListAuthorizationRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuthorization not implemented")
}
func (*UnimplementedStoreServiceServer) CreateAuthorization(ctx context.Context, req *CreateAuthorizationParams) (*Authorization, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuthorization not implemented")
}
func (*UnimplementedStoreServiceServer) RetrieveAuthorization(ctx context.Context, req *RetrieveAuthorizationParams) (*Authorization, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveAuthorization not implemented")
}
func (*UnimplementedStoreServiceServer) GetMe(ctx context.Context, req *empty.Empty) (*Me, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMe not implemented")
}
func (*UnimplementedStoreServiceServer) QueryData(ctx context.Context, req *QueryParams) (*QueryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryData not implemented")
}
func (*UnimplementedStoreServiceServer) InsertData(ctx context.Context, req *InsertDataParams) (*InsertDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertData not implemented")
}

func RegisterStoreServiceServer(s *grpc.Server, srv StoreServiceServer) {
	s.RegisterService(&_StoreService_serviceDesc, srv)
}

func _StoreService_CheckSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).CheckSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/CheckSetup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).CheckSetup(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Setup(ctx, req.(*SetupParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).SignIn(ctx, req.(*SignInParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).SignOut(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListAllBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllBucketsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListAllBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/ListAllBuckets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListAllBuckets(ctx, req.(*ListAllBucketsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RetrieveBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBucketParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RetrieveBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/RetrieveBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RetrieveBucket(ctx, req.(*RetrieveBucketParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RetrieveBucketLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetreiveBucketLogParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RetrieveBucketLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/RetrieveBucketLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RetrieveBucketLog(ctx, req.(*RetreiveBucketLogParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/DeleteBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteBucket(ctx, req.(*DeleteBucketParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuthorizationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/ListAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListAuthorization(ctx, req.(*ListAuthorizationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_CreateAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthorizationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).CreateAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/CreateAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).CreateAuthorization(ctx, req.(*CreateAuthorizationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RetrieveAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveAuthorizationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RetrieveAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/RetrieveAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RetrieveAuthorization(ctx, req.(*RetrieveAuthorizationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/GetMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetMe(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_QueryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).QueryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/QueryData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).QueryData(ctx, req.(*QueryParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_InsertData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertDataParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).InsertData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/InsertData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).InsertData(ctx, req.(*InsertDataParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckSetup",
			Handler:    _StoreService_CheckSetup_Handler,
		},
		{
			MethodName: "Setup",
			Handler:    _StoreService_Setup_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _StoreService_SignIn_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _StoreService_SignOut_Handler,
		},
		{
			MethodName: "ListAllBuckets",
			Handler:    _StoreService_ListAllBuckets_Handler,
		},
		{
			MethodName: "RetrieveBucket",
			Handler:    _StoreService_RetrieveBucket_Handler,
		},
		{
			MethodName: "RetrieveBucketLog",
			Handler:    _StoreService_RetrieveBucketLog_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _StoreService_DeleteBucket_Handler,
		},
		{
			MethodName: "ListAuthorization",
			Handler:    _StoreService_ListAuthorization_Handler,
		},
		{
			MethodName: "CreateAuthorization",
			Handler:    _StoreService_CreateAuthorization_Handler,
		},
		{
			MethodName: "RetrieveAuthorization",
			Handler:    _StoreService_RetrieveAuthorization_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _StoreService_GetMe_Handler,
		},
		{
			MethodName: "QueryData",
			Handler:    _StoreService_QueryData_Handler,
		},
		{
			MethodName: "InsertData",
			Handler:    _StoreService_InsertData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/main.proto",
}
