// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/main.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("protocol/main.proto", fileDescriptor_9e8e7d5cf664e777) }

var fileDescriptor_9e8e7d5cf664e777 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0xd1, 0x4a, 0x86, 0x30,
	0x18, 0x86, 0x7f, 0x08, 0x22, 0xc6, 0xcf, 0x5f, 0x2e, 0x3a, 0xb1, 0x10, 0xf2, 0x02, 0x0c, 0xea,
	0x02, 0xa2, 0xf0, 0x50, 0x30, 0xf4, 0xc4, 0xd3, 0x29, 0x1f, 0x39, 0x9a, 0x4e, 0xb6, 0x4f, 0x0f,
	0xba, 0x94, 0xae, 0x36, 0xd8, 0xb4, 0x6d, 0x48, 0xff, 0xe1, 0xde, 0xe7, 0xfd, 0x1e, 0xde, 0x91,
	0xdb, 0x49, 0x49, 0x94, 0x9d, 0x14, 0x4f, 0x03, 0xe3, 0x63, 0x66, 0x5e, 0xf4, 0x6a, 0x0b, 0xe3,
	0xbb, 0x3f, 0xdc, 0xce, 0xdd, 0x17, 0xa0, 0x2d, 0xc4, 0xee, 0x8a, 0xcd, 0xd8, 0xdb, 0xf0, 0xf9,
	0xe7, 0x82, 0x1c, 0x6b, 0x94, 0x0a, 0x6a, 0x50, 0x0b, 0xef, 0x80, 0x96, 0xe4, 0x54, 0x70, 0x8d,
	0x6f, 0x42, 0xbc, 0x9b, 0x63, 0x4d, 0x93, 0x6c, 0x3b, 0xcc, 0x42, 0xf2, 0xc1, 0x14, 0x1b, 0x74,
	0x7c, 0xff, 0x1f, 0xaf, 0x40, 0xa7, 0x07, 0x9a, 0x93, 0x53, 0x05, 0xa8, 0x38, 0x2c, 0x60, 0x73,
	0x5f, 0x18, 0x92, 0x55, 0x78, 0xe3, 0xb8, 0xcd, 0xd3, 0x03, 0x6d, 0x48, 0x14, 0x76, 0x0b, 0xf9,
	0x49, 0x1f, 0x43, 0x11, 0x70, 0x0f, 0xae, 0xae, 0xe4, 0x4c, 0xc5, 0xee, 0x7b, 0x25, 0xc7, 0x1c,
	0x04, 0xe0, 0xb6, 0xee, 0xc1, 0x5d, 0xf8, 0xf9, 0xea, 0xbb, 0x76, 0xb4, 0x9c, 0xac, 0xa0, 0x21,
	0x91, 0xf9, 0xf7, 0x8c, 0xbd, 0x54, 0xfc, 0x9b, 0x21, 0x97, 0xa3, 0x3f, 0x6d, 0x07, 0xf7, 0xd3,
	0x76, 0x15, 0x63, 0x6e, 0x2f, 0x4d, 0xe1, 0xe5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x64, 0x7b, 0xa9,
	0x3c, 0xf0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreServiceClient interface {
	// Bucket
	ListAllBuckets(ctx context.Context, in *ListAllBucketsParams, opts ...grpc.CallOption) (*ListAllBucketsRes, error)
	RetrieveBucket(ctx context.Context, in *RetrieveBucketParams, opts ...grpc.CallOption) (*Bucket, error)
	RetrieveBucketLog(ctx context.Context, in *RetreiveBucketLogParams, opts ...grpc.CallOption) (*RetreiveBucketLogRes, error)
	DeleteBucket(ctx context.Context, in *DeleteBucketParams, opts ...grpc.CallOption) (*OpRes, error)
	// Auth
	ListAuthorization(ctx context.Context, in *ListAuthorizationParams, opts ...grpc.CallOption) (*ListAuthorizationRes, error)
}

type storeServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoreServiceClient(cc *grpc.ClientConn) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) ListAllBuckets(ctx context.Context, in *ListAllBucketsParams, opts ...grpc.CallOption) (*ListAllBucketsRes, error) {
	out := new(ListAllBucketsRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/ListAllBuckets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RetrieveBucket(ctx context.Context, in *RetrieveBucketParams, opts ...grpc.CallOption) (*Bucket, error) {
	out := new(Bucket)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/RetrieveBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RetrieveBucketLog(ctx context.Context, in *RetreiveBucketLogParams, opts ...grpc.CallOption) (*RetreiveBucketLogRes, error) {
	out := new(RetreiveBucketLogRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/RetrieveBucketLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteBucket(ctx context.Context, in *DeleteBucketParams, opts ...grpc.CallOption) (*OpRes, error) {
	out := new(OpRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/DeleteBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListAuthorization(ctx context.Context, in *ListAuthorizationParams, opts ...grpc.CallOption) (*ListAuthorizationRes, error) {
	out := new(ListAuthorizationRes)
	err := c.cc.Invoke(ctx, "/protocol.StoreService/ListAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
type StoreServiceServer interface {
	// Bucket
	ListAllBuckets(context.Context, *ListAllBucketsParams) (*ListAllBucketsRes, error)
	RetrieveBucket(context.Context, *RetrieveBucketParams) (*Bucket, error)
	RetrieveBucketLog(context.Context, *RetreiveBucketLogParams) (*RetreiveBucketLogRes, error)
	DeleteBucket(context.Context, *DeleteBucketParams) (*OpRes, error)
	// Auth
	ListAuthorization(context.Context, *ListAuthorizationParams) (*ListAuthorizationRes, error)
}

// UnimplementedStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServiceServer struct {
}

func (*UnimplementedStoreServiceServer) ListAllBuckets(ctx context.Context, req *ListAllBucketsParams) (*ListAllBucketsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllBuckets not implemented")
}
func (*UnimplementedStoreServiceServer) RetrieveBucket(ctx context.Context, req *RetrieveBucketParams) (*Bucket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBucket not implemented")
}
func (*UnimplementedStoreServiceServer) RetrieveBucketLog(ctx context.Context, req *RetreiveBucketLogParams) (*RetreiveBucketLogRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBucketLog not implemented")
}
func (*UnimplementedStoreServiceServer) DeleteBucket(ctx context.Context, req *DeleteBucketParams) (*OpRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (*UnimplementedStoreServiceServer) ListAuthorization(ctx context.Context, req *ListAuthorizationParams) (*ListAuthorizationRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuthorization not implemented")
}

func RegisterStoreServiceServer(s *grpc.Server, srv StoreServiceServer) {
	s.RegisterService(&_StoreService_serviceDesc, srv)
}

func _StoreService_ListAllBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllBucketsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListAllBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/ListAllBuckets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListAllBuckets(ctx, req.(*ListAllBucketsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RetrieveBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBucketParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RetrieveBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/RetrieveBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RetrieveBucket(ctx, req.(*RetrieveBucketParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RetrieveBucketLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetreiveBucketLogParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RetrieveBucketLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/RetrieveBucketLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RetrieveBucketLog(ctx, req.(*RetreiveBucketLogParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/DeleteBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteBucket(ctx, req.(*DeleteBucketParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuthorizationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.StoreService/ListAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListAuthorization(ctx, req.(*ListAuthorizationParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAllBuckets",
			Handler:    _StoreService_ListAllBuckets_Handler,
		},
		{
			MethodName: "RetrieveBucket",
			Handler:    _StoreService_RetrieveBucket_Handler,
		},
		{
			MethodName: "RetrieveBucketLog",
			Handler:    _StoreService_RetrieveBucketLog_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _StoreService_DeleteBucket_Handler,
		},
		{
			MethodName: "ListAuthorization",
			Handler:    _StoreService_ListAuthorization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/main.proto",
}
