// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/query.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryParams struct {
	QueryString          string   `protobuf:"bytes,1,opt,name=queryString,proto3" json:"queryString,omitempty"`
	Org                  string   `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParams) Reset()         { *m = QueryParams{} }
func (m *QueryParams) String() string { return proto.CompactTextString(m) }
func (*QueryParams) ProtoMessage()    {}
func (*QueryParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc44bd2daa7c7ae6, []int{0}
}

func (m *QueryParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParams.Unmarshal(m, b)
}
func (m *QueryParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParams.Marshal(b, m, deterministic)
}
func (m *QueryParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParams.Merge(m, src)
}
func (m *QueryParams) XXX_Size() int {
	return xxx_messageInfo_QueryParams.Size(m)
}
func (m *QueryParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParams proto.InternalMessageInfo

func (m *QueryParams) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

func (m *QueryParams) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

type Record struct {
	Zone                 string   `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Count                string   `protobuf:"bytes,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc44bd2daa7c7ae6, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Record) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Record) GetCount() string {
	if m != nil {
		return m.Count
	}
	return ""
}

type QueryRes struct {
	Record               []*Record `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryRes) Reset()         { *m = QueryRes{} }
func (m *QueryRes) String() string { return proto.CompactTextString(m) }
func (*QueryRes) ProtoMessage()    {}
func (*QueryRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc44bd2daa7c7ae6, []int{2}
}

func (m *QueryRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRes.Unmarshal(m, b)
}
func (m *QueryRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRes.Marshal(b, m, deterministic)
}
func (m *QueryRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRes.Merge(m, src)
}
func (m *QueryRes) XXX_Size() int {
	return xxx_messageInfo_QueryRes.Size(m)
}
func (m *QueryRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRes proto.InternalMessageInfo

func (m *QueryRes) GetRecord() []*Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type RowMetric struct {
	Fields               map[string]*any.Any  `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags                 map[string]string    `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RowMetric) Reset()         { *m = RowMetric{} }
func (m *RowMetric) String() string { return proto.CompactTextString(m) }
func (*RowMetric) ProtoMessage()    {}
func (*RowMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc44bd2daa7c7ae6, []int{3}
}

func (m *RowMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowMetric.Unmarshal(m, b)
}
func (m *RowMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowMetric.Marshal(b, m, deterministic)
}
func (m *RowMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowMetric.Merge(m, src)
}
func (m *RowMetric) XXX_Size() int {
	return xxx_messageInfo_RowMetric.Size(m)
}
func (m *RowMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_RowMetric.DiscardUnknown(m)
}

var xxx_messageInfo_RowMetric proto.InternalMessageInfo

func (m *RowMetric) GetFields() map[string]*any.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *RowMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RowMetric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RowMetric) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type InsertDataParams struct {
	Bucket               string       `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Org                  string       `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Metrics              []*RowMetric `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InsertDataParams) Reset()         { *m = InsertDataParams{} }
func (m *InsertDataParams) String() string { return proto.CompactTextString(m) }
func (*InsertDataParams) ProtoMessage()    {}
func (*InsertDataParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc44bd2daa7c7ae6, []int{4}
}

func (m *InsertDataParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertDataParams.Unmarshal(m, b)
}
func (m *InsertDataParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertDataParams.Marshal(b, m, deterministic)
}
func (m *InsertDataParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertDataParams.Merge(m, src)
}
func (m *InsertDataParams) XXX_Size() int {
	return xxx_messageInfo_InsertDataParams.Size(m)
}
func (m *InsertDataParams) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertDataParams.DiscardUnknown(m)
}

var xxx_messageInfo_InsertDataParams proto.InternalMessageInfo

func (m *InsertDataParams) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *InsertDataParams) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *InsertDataParams) GetMetrics() []*RowMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type InsertDataRes struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertDataRes) Reset()         { *m = InsertDataRes{} }
func (m *InsertDataRes) String() string { return proto.CompactTextString(m) }
func (*InsertDataRes) ProtoMessage()    {}
func (*InsertDataRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc44bd2daa7c7ae6, []int{5}
}

func (m *InsertDataRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertDataRes.Unmarshal(m, b)
}
func (m *InsertDataRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertDataRes.Marshal(b, m, deterministic)
}
func (m *InsertDataRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertDataRes.Merge(m, src)
}
func (m *InsertDataRes) XXX_Size() int {
	return xxx_messageInfo_InsertDataRes.Size(m)
}
func (m *InsertDataRes) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertDataRes.DiscardUnknown(m)
}

var xxx_messageInfo_InsertDataRes proto.InternalMessageInfo

func (m *InsertDataRes) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParams)(nil), "protocol.QueryParams")
	proto.RegisterType((*Record)(nil), "protocol.Record")
	proto.RegisterType((*QueryRes)(nil), "protocol.QueryRes")
	proto.RegisterType((*RowMetric)(nil), "protocol.RowMetric")
	proto.RegisterMapType((map[string]*any.Any)(nil), "protocol.RowMetric.FieldsEntry")
	proto.RegisterMapType((map[string]string)(nil), "protocol.RowMetric.TagsEntry")
	proto.RegisterType((*InsertDataParams)(nil), "protocol.InsertDataParams")
	proto.RegisterType((*InsertDataRes)(nil), "protocol.InsertDataRes")
}

func init() { proto.RegisterFile("protocol/query.proto", fileDescriptor_dc44bd2daa7c7ae6) }

var fileDescriptor_dc44bd2daa7c7ae6 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x61, 0xcb, 0xd3, 0x30,
	0x10, 0xa6, 0xed, 0xde, 0xfa, 0xf6, 0x8a, 0x30, 0x62, 0x91, 0x5a, 0x90, 0xb7, 0x14, 0x84, 0x32,
	0xb0, 0xc3, 0x29, 0x4c, 0xfc, 0x36, 0xd0, 0x81, 0x1f, 0x44, 0x8d, 0xfb, 0x03, 0x59, 0x97, 0x95,
	0xb2, 0x36, 0x99, 0x49, 0xaa, 0xd4, 0x7f, 0xe7, 0x3f, 0x93, 0xa4, 0xe9, 0x2c, 0xef, 0xf6, 0xed,
	0xee, 0xf2, 0xdc, 0x73, 0x4f, 0x9e, 0x3b, 0x88, 0xce, 0x82, 0x2b, 0x5e, 0xf2, 0x66, 0xf9, 0xb3,
	0xa3, 0xa2, 0x2f, 0x4c, 0x8a, 0xee, 0xc7, 0x6a, 0xf2, 0x50, 0x71, 0x5e, 0x35, 0x74, 0x69, 0x0a,
	0xfb, 0xee, 0xb8, 0x54, 0x75, 0x4b, 0xa5, 0x22, 0xed, 0x79, 0x80, 0x26, 0x2f, 0x1e, 0x03, 0x08,
	0xb3, 0x2c, 0xd9, 0x06, 0xc2, 0xef, 0x9a, 0xf4, 0x1b, 0x11, 0xa4, 0x95, 0x28, 0x85, 0xd0, 0xcc,
	0xf8, 0xa1, 0x44, 0xcd, 0xaa, 0xd8, 0x49, 0x9d, 0x3c, 0xc0, 0xd3, 0x12, 0x9a, 0x83, 0xc7, 0x45,
	0x15, 0xbb, 0xe6, 0x45, 0x87, 0xd9, 0x16, 0x7c, 0x4c, 0x4b, 0x2e, 0x0e, 0x08, 0xc1, 0xec, 0x0f,
	0x67, 0xd4, 0xb6, 0x99, 0x58, 0xd7, 0x0e, 0x44, 0x51, 0xdb, 0x60, 0x62, 0x14, 0xc1, 0x5d, 0xc9,
	0x3b, 0xa6, 0x62, 0xcf, 0x14, 0x87, 0x24, 0x7b, 0x07, 0xf7, 0x46, 0x0a, 0xa6, 0x12, 0xe5, 0xe0,
	0x0b, 0xc3, 0x19, 0x3b, 0xa9, 0x97, 0x87, 0xab, 0x79, 0x31, 0xfe, 0xb6, 0x18, 0x66, 0x61, 0xfb,
	0x9e, 0xfd, 0x75, 0x21, 0xc0, 0xfc, 0xf7, 0x17, 0xaa, 0x44, 0x5d, 0xa2, 0x35, 0xf8, 0xc7, 0x9a,
	0x36, 0x07, 0x69, 0xfb, 0x1e, 0x26, 0x7d, 0x23, 0xa8, 0xd8, 0x1a, 0xc4, 0x27, 0xa6, 0x44, 0x8f,
	0x2d, 0x5c, 0xcb, 0x64, 0xa4, 0xbd, 0xc8, 0xd4, 0x31, 0x7a, 0x03, 0x33, 0x45, 0x2a, 0x19, 0x7b,
	0x86, 0xea, 0xe5, 0x2d, 0xaa, 0x1d, 0xa9, 0x2c, 0x91, 0x81, 0xa2, 0x05, 0xb8, 0x4a, 0xc6, 0xb3,
	0xd4, 0xc9, 0xc3, 0x55, 0x52, 0x0c, 0xb6, 0x17, 0xa3, 0xed, 0xc5, 0x6e, 0xdc, 0x0b, 0x76, 0x95,
	0x4c, 0xbe, 0x42, 0x38, 0x51, 0xa2, 0x8d, 0x3d, 0xd1, 0xde, 0x7a, 0xa7, 0x43, 0xb4, 0x80, 0xbb,
	0x5f, 0xa4, 0xe9, 0x06, 0x51, 0xe1, 0x2a, 0xba, 0xe2, 0xdb, 0xb0, 0x1e, 0x0f, 0x90, 0x0f, 0xee,
	0x7b, 0x27, 0x59, 0x43, 0x70, 0xd1, 0x73, 0x83, 0x2e, 0x9a, 0xd2, 0x05, 0x93, 0xc6, 0xec, 0x04,
	0xf3, 0xcf, 0x4c, 0x52, 0xa1, 0x3e, 0x12, 0x45, 0xec, 0x25, 0x3c, 0x07, 0x7f, 0xdf, 0x95, 0x27,
	0xaa, 0x2c, 0x85, 0xcd, 0xae, 0xf7, 0x8f, 0x5e, 0xc3, 0x93, 0xd6, 0xb8, 0x31, 0x3a, 0xf5, 0xec,
	0x86, 0x53, 0x78, 0xc4, 0x64, 0xaf, 0xe0, 0xe9, 0xff, 0x61, 0x7a, 0xd7, 0x97, 0x6b, 0xd0, 0x83,
	0x3c, 0x7b, 0x0d, 0x7b, 0xdf, 0x70, 0xbc, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xb5, 0x4d,
	0x95, 0xfd, 0x02, 0x00, 0x00,
}
