# service
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dim-edge-influxdb-1
  name: dim-edge-influxdb-1
spec:
  externalTrafficPolicy: Local
  ports:
    - name: '9999'
      port: 9999
      targetPort: 9999
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: dim-edge-influxdb-1
