// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/main.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("proto/main.proto", fileDescriptor_098391ad7281b52b) }

var fileDescriptor_098391ad7281b52b = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0xcc, 0xcc, 0xd3, 0x03, 0x33, 0x85, 0x58, 0xc1, 0x94, 0x94, 0x10, 0x44,
	0x22, 0xa9, 0x34, 0x39, 0x3b, 0xb5, 0x04, 0x22, 0x65, 0xb4, 0x82, 0x89, 0x8b, 0x27, 0xb8, 0x24,
	0xbf, 0x28, 0x35, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x93, 0x8b, 0xcf, 0x27, 0xb3,
	0xb8, 0xc4, 0x31, 0x27, 0xc7, 0x09, 0xac, 0xae, 0x58, 0x48, 0x1a, 0xa2, 0x54, 0x0f, 0x55, 0x38,
	0x20, 0xb1, 0x28, 0x31, 0xb7, 0x58, 0x4a, 0x02, 0xab, 0x64, 0x50, 0x6a, 0xb1, 0x12, 0x83, 0x90,
	0x1d, 0x17, 0x5f, 0x50, 0x6a, 0x49, 0x51, 0x66, 0x6a, 0x59, 0x2a, 0x44, 0x1c, 0x6e, 0x14, 0xaa,
	0x30, 0xd4, 0x28, 0x5e, 0xa8, 0x24, 0x44, 0x50, 0x89, 0x41, 0x28, 0x88, 0x4b, 0x10, 0x55, 0xa1,
	0x4f, 0x7e, 0xba, 0x90, 0x1c, 0x92, 0x11, 0xa9, 0x99, 0x48, 0x32, 0x50, 0x53, 0xa4, 0x71, 0xc9,
	0x43, 0xdc, 0x64, 0xc9, 0xc5, 0xe3, 0x92, 0x9a, 0x93, 0x5a, 0x02, 0x73, 0x91, 0x24, 0x54, 0x39,
	0xb2, 0x20, 0xd4, 0x24, 0x1e, 0xa8, 0x94, 0x7f, 0x01, 0x58, 0x6b, 0x12, 0x1b, 0x98, 0x6b, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x7b, 0xd7, 0x7b, 0x60, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreServiceClient interface {
	ListAllBuckets(ctx context.Context, in *ListAllBucketsParams, opts ...grpc.CallOption) (*ListAllBucketsRes, error)
	RetrieveBucket(ctx context.Context, in *RetrieveBucketParams, opts ...grpc.CallOption) (*Bucket, error)
	RetrieveBucketLog(ctx context.Context, in *RetreiveBucketLogParams, opts ...grpc.CallOption) (*RetreiveBucketLogRes, error)
	DeleteBucket(ctx context.Context, in *DeleteBucketParams, opts ...grpc.CallOption) (*OpRes, error)
}

type storeServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoreServiceClient(cc *grpc.ClientConn) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) ListAllBuckets(ctx context.Context, in *ListAllBucketsParams, opts ...grpc.CallOption) (*ListAllBucketsRes, error) {
	out := new(ListAllBucketsRes)
	err := c.cc.Invoke(ctx, "/proto.StoreService/ListAllBuckets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RetrieveBucket(ctx context.Context, in *RetrieveBucketParams, opts ...grpc.CallOption) (*Bucket, error) {
	out := new(Bucket)
	err := c.cc.Invoke(ctx, "/proto.StoreService/RetrieveBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RetrieveBucketLog(ctx context.Context, in *RetreiveBucketLogParams, opts ...grpc.CallOption) (*RetreiveBucketLogRes, error) {
	out := new(RetreiveBucketLogRes)
	err := c.cc.Invoke(ctx, "/proto.StoreService/RetrieveBucketLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteBucket(ctx context.Context, in *DeleteBucketParams, opts ...grpc.CallOption) (*OpRes, error) {
	out := new(OpRes)
	err := c.cc.Invoke(ctx, "/proto.StoreService/DeleteBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
type StoreServiceServer interface {
	ListAllBuckets(context.Context, *ListAllBucketsParams) (*ListAllBucketsRes, error)
	RetrieveBucket(context.Context, *RetrieveBucketParams) (*Bucket, error)
	RetrieveBucketLog(context.Context, *RetreiveBucketLogParams) (*RetreiveBucketLogRes, error)
	DeleteBucket(context.Context, *DeleteBucketParams) (*OpRes, error)
}

// UnimplementedStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServiceServer struct {
}

func (*UnimplementedStoreServiceServer) ListAllBuckets(ctx context.Context, req *ListAllBucketsParams) (*ListAllBucketsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllBuckets not implemented")
}
func (*UnimplementedStoreServiceServer) RetrieveBucket(ctx context.Context, req *RetrieveBucketParams) (*Bucket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBucket not implemented")
}
func (*UnimplementedStoreServiceServer) RetrieveBucketLog(ctx context.Context, req *RetreiveBucketLogParams) (*RetreiveBucketLogRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBucketLog not implemented")
}
func (*UnimplementedStoreServiceServer) DeleteBucket(ctx context.Context, req *DeleteBucketParams) (*OpRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBucket not implemented")
}

func RegisterStoreServiceServer(s *grpc.Server, srv StoreServiceServer) {
	s.RegisterService(&_StoreService_serviceDesc, srv)
}

func _StoreService_ListAllBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllBucketsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListAllBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreService/ListAllBuckets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListAllBuckets(ctx, req.(*ListAllBucketsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RetrieveBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBucketParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RetrieveBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreService/RetrieveBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RetrieveBucket(ctx, req.(*RetrieveBucketParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RetrieveBucketLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetreiveBucketLogParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RetrieveBucketLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreService/RetrieveBucketLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RetrieveBucketLog(ctx, req.(*RetreiveBucketLogParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreService/DeleteBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteBucket(ctx, req.(*DeleteBucketParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAllBuckets",
			Handler:    _StoreService_ListAllBuckets_Handler,
		},
		{
			MethodName: "RetrieveBucket",
			Handler:    _StoreService_RetrieveBucket_Handler,
		},
		{
			MethodName: "RetrieveBucketLog",
			Handler:    _StoreService_RetrieveBucketLog_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _StoreService_DeleteBucket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/main.proto",
}
